-- phpMyAdmin SQL Dump
-- version 5.2.0
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Sep 22, 2023 at 05:53 PM
-- Server version: 10.4.25-MariaDB
-- PHP Version: 8.1.10

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `a_etman`
--

--
-- Dumping data for table `category_translations`
--

INSERT INTO `category_translations` (`id`, `category_id`, `locale`, `slug`, `name`, `des`, `g_title`, `g_des`, `body_h1`, `breadcrumb`) VALUES
(1, 1, 'ar', 'الأشرطة-ذاتية-اللصق', 'الأشرطة ذاتية اللصق', 'الأشرطة ذاتية اللصق مصنوعة من مادة لاصقة ذات أساس مائي مطلية بغشاء BOPP.\r\nإنها مناسبة للاستخدامات المختلفة وفقًا لسمكها. \r\n\r\nإنه لزج (لزج) بدون أي حرارة أو مذيب للتنشيط ويلتصق بضغط خفيف. تتطلب هذه الأشرطة عادةً عامل تحرير على ظهرها أو بطانة تحرير لتغطية المادة اللاصقة.\r\n\r\nنحن ننتج مجموعة متنوعة من المنتجات لتلبية جميع الاحتياجات الخاصة بمتطلبات سوق التعبئة والتغليف للتغليف يمكن تزويده بـ (التصاق عالي ، قابل للطباعة ، مقاوم للعوامل الجوية وقوة شد عالية).\r\n\r\nمن ناحية أخرى ، لدينا قاعدة مذيب من المطاط الطبيعي ، تستخدم للثلاجات والأفران.\r\nوالتى يتم استخدمها  أثناء تصدير الفواكه والخضروات ، وكذلك يتم استخدمها مع درجات الحرارة العالية ودرجة الحرارة المنخفضة للغاية.', 'عتمان جروب متخصصون فى صناعة الأشرطة ذاتية اللصق بجميع انواعها', 'الأشرطة ذاتية اللصق مصنوعة من مادة لاصقة ذات أساس مائي مطلية بغشاء BOPP. إنها مناسبة للاستخدامات المختلفة وفقًا لسمكها. إنه لزج (لزج) بدون أي حرارة أو مذيب', NULL, NULL),
(2, 1, 'en', 'self-adhesive-tape', 'Self Adhesive Tape', 'The packing adhesive tapes is made from water based adhesive coated on BOPP film .It suitable for different weight requirement according to its thickness.\r\n\r\nIt is sticky (tacky) without any heat or solvent for activation and adheres with light pressure. These tapes usually require a release agent on their backing or a release liner to cover the adhesive. \r\n\r\nWe produce variety of products to meet all special needs for economical general, medium heavy-duty and special heavy duty packing.\r\n \r\nIt can be provided with (high adhesion, printable, weather-resistance and high tensile strength).\r\n\r\nOn other hand we have Natural rubber solvent base , using for fridges and ovens . \r\nAs we have needs in sealing cartons go with the Refrigeration during export of fruits and vegetable , also use for seal in high temperature and very low temperature .', 'Etman Group specializes in the manufacture of self-adhesive tapes', 'The packing adhesive tapes is made from water based adhesive coated on BOPP film .It suitable for different weight requirement according to its thickness.', NULL, NULL),
(3, 3, 'ar', 'الأشرطة-ذاتية-اللصق-شرائط-التعبئة-والتغليف', 'شرائط التعبئة والتغليف', 'الأشرطة ذاتية اللصق المستخدمة للتغليف مصنوعة من مادة لاصقة ذات أساس مائي مطلية بغشاء BOPP.نحن فى عتمان جروب ننتج مجموعة متنوعة من المنتجات لتلبية جميع احتياجات السوق المحلى \r\nتستخدم في المستودعات والمخازن والمصانع وكذلك الاستخدام المنزلي والمكتبي. يمكن استخدام الاشرطة ذاتية اللصق في عمليات نقل الاثاث ، وشركات الشحن ، والبريد ،وكذلك تستخدم فى عمليات تخزين وتنظيم الأدوات المنزلية', 'الأشرطة ذاتية اللصق | شرائط التعبئة والتغليف', 'الأشرطة ذاتية اللصق المستخدمة للتغليف مصنوعة من مادة لاصقة ذات أساس مائي مطلية بغشاء BOPP.نحن ننتج مجموعة متنوعة من المنتجات لتلبية جميع احتياجات السوق المحلى ', NULL, NULL),
(4, 3, 'en', 'Self-Adhesive-Tape-Packaging-Tape', 'Packaging Tape', 'The self-adhesive tapes used for packing are made of a water-based adhesive that is coated with BOPP film. We produce a variety of products to meet all the needs of the local market. \r\n\r\nApply at the depot, home and office use. The tape could be used for home removals, shipping and mailing, for storing and organizing household items', 'Self Adhesive Tape | Packaging Tape', 'The self-adhesive tapes used for packing are made of a water-based adhesive that is coated with BOPP film. We produce a variety of products to meet all need', NULL, NULL),
(5, 6, 'ar', 'الأشرطة-ذاتية-اللصق-السوليتب-المكتبى', 'السوليتب المكتبى', 'السوليتب المكتبى مصنوع من مادة لاصقة أكريليك مائية مطلية بأفلام BOOP.\r\nإنه مناسب للاستخدام للصق الورق ، وتغليف الهدايا وتثبيتها ، وهو سهل الاستخدام كما انه يسهل تمزيقه بدون استخدام القطاعات المخصصة لذلك\r\nمتوفر بأحجام وعروض وتصاميم مختلفة لتلبية متطلبات العميل الخاصة.\r\nالاستعمال: تغليف الهدايا ، التعبئة الخفيفة ، والحرف الفنية ، الاستخدام المكتبي ، إصلاح الورق وتقوية المستندات.', 'الأشرطة ذاتية اللصق | السوليتب المكتبى', 'السوليتب المكتبى مصنوع من مادة لاصقة أكريليك مائية مطلية بأفلام BOOP.\r\nإنه مناسب للاستخدام للصق الورق ، وتغليف الهدايا وتثبيتها ، ', NULL, NULL),
(6, 6, 'en', 'Self-Adhesive-Tape-Stationary-Tape', 'Stationery Tape', 'Stationary tape is made with water based acrylic adhesive coated on BOOP films . \r\nIt’s suitable for paper mending , general sealing , gift wrapping and fixing , also it can be provided as an easy tear that use without dispensers . \r\nAvailable with different sizes, widths and designs to meet the client’s special requirements .\r\nUsage : gift wrapping , light packing , art craft , office use , paper mending and reinforcing documents .', 'Self Adhesive Tape | Stationary Tap', 'Stationary tape is made with water based acrylic adhesive coated on BOOP films . \r\nIt’s suitable for paper mending , general sealing , gift wrapping  ', NULL, NULL),
(7, 7, 'ar', 'الأشرطة-ذاتية-اللصق-ماسك-تيب', 'ماسك تيب', 'شرائط الماسك تيب مصنوع من خامات ورقية مغطى بمادة لاصقة مطاطية يمكن استخدامها في تطبيقات الحماية والتثبيت والأغراض العامة. إنه متوفر بأحجام مختلفة لتلبية متطلبات العميل الخاصة. تستخدم بدرجات حرارة مختلفة للدهان السيارات. وتغطية الأسطح أثناء الرش أو الطلاء. وكذلك حماية الأسطح المعدنية والبلاستيكية والزجاجية.', 'الأشرطة ذاتية اللصق | ماسك تيب تستخدم لاغراض الحماية والتثبيت', 'شرائط الماسك تيب مصنوع من خامات ورقية مغطى بمادة لاصقة مطاطية يمكن استخدامها في تطبيقات الحماية والتثبيت والأغراض العامة. إنه متوفر بأحجام مختلفة ', NULL, NULL),
(8, 7, 'en', 'Self-Adhesive-Tape-Masking-Tape', 'Masking Tape', 'Masking tape is made of crepe paper that coated with rubber adhesive that could use for sealing , holding and general purpose applications. It’s available in different sizes , widths and designs to meet client’s special requirements. It used in different temperature degrees for painting and car’s spray. and Covering surfaces during spraying or painting. and also Protection of metal , plastic and glasses surfaces .', 'Self Adhesive Tape | Masking Tape use for sealing and holding', 'Masking tape is made of crepe paper that coated with rubber adhesive that could use for sealing , holding and general purpose applications. ', NULL, NULL),
(9, 10, 'ar', 'الأشرطة-ذاتية-اللصق-شريط-العزل-الكهربائي', 'شرائط العزل الكهربائي', 'شرائط العزل الكهربائي PVC مصنوعة من البولي فينيل كلوريد (spvc) المطلي بمادة لاصقة حساسة للضغط، كما أنه يعتبر مقاومًا جيدًا لدرجات الحرارة والرطوبة والجهد العالي وتطبيقات الحماية. متوفر بأحجام مختلفة. يستخدم فى تطبيقات الاعمال الكهربائية', 'الأشرطة ذاتية اللصق | شريط العزل الكهربائي ', 'شرائط العزل الكهربائي PVC مصنوعة من البولي فينيل كلوريد (spvc) المطلي بمادة لاصقة حساسة للضغط، كما أنه يعتبر مقاومًا جيدًا لدرجات الحرارة والرطوبة والجهد', NULL, NULL),
(10, 10, 'en', 'Self-Adhesive-Tape-Electrical-Insulating-Tape', 'Electrical Insulating Tape', 'Electrical Insulating Tape PVC insulating tape is made from soft polyvinyl chloride (spvc) which is coated with rubber pressure -sensitive adhesive , it’s also considered good resistant to temperature , moisture , high voltage and protection applications .\r\nIt’s available in different sizes .Usage in Strong tensile strength use in electric work application .', 'Self Adhesive Tape | Electrical Insulating Tape', 'Electrical Insulating Tape PVC insulating tape is made from soft polyvinyl chloride (spvc) which is coated with rubber pressure -sensitive adhesive ', NULL, NULL),
(11, 12, 'ar', 'الأشرطة-ذاتية-اللصق-شرائط-مزدوجة-الوجهين', 'شرائط مزدوجة الوجهين', 'الشرائط مزدوجة الوجهين مصنوعه ومغلفه بمادة لاصقة مذيبة. يتم استخدامه للزينة والخدمات البريدية. متوفره بأحجام وعرض مختلفة لتلبية لمتطلبات العملاء الخاصة. الاستخدام ملاحظات عامة ، تثبيت العناصر والصور ، تغليف الهدايا والخدمات البريدية.', 'الأشرطة ذاتية اللصق | شرائط مزدوجة الوجهين', 'الشرائط مزدوجة الوجهين مصنوعه ومغلفه بمادة لاصقة مذيبة. يتم استخدامه للزينة والخدمات البريدية. متوفره بأحجام وعرض مختلفة لتلبية لمتطلبات العملاء الخاصة.', NULL, NULL),
(12, 12, 'en', 'self-adhesive-tape-double-sided-tape', 'Double Sided Tape', 'Double side tissue tape is made and coated with solvent adhesive . It’s used for decoration and postal services. It’s available in different sizes , widths and designs to meet client’s special requirements. Usage Public notes , fixing items and photos , gift wrapping and postal services .', 'Self Adhesive Tape | Double Sided Tape', 'Double side tissue tape is made and coated with solvent adhesive . It’s used for decoration and postal services. It’s available in different sizes', NULL, NULL),
(13, 13, 'ar', 'شرائط-ذاتية-اللصق-ملونه', 'شرائط ذاتية اللصق ملونه', 'الشرائط ذاتية اللصق الملونه مصنوعه من أغشية BOPP اللاصقة المائية المصنوعة من الأكريليك ، ويمكن توفيره بألوان عديدة لمساعدة العملاء في عمليات تنظيم وفرز المنتجات اثناء التخزين او النقل متوفر بأحجام وعرض مختلفة لتلبية جميع احتياجات و متطلبات العملاء الخاصة', 'الأشرطة ذاتية اللصق | شرائط ذاتية اللصق ملونه', 'الشرائط ذاتية اللصق الملونه مصنوعه من أغشية BOPP اللاصقة المائية المصنوعة من الأكريليك، ويمكن توفيره بألوان عديدة لمساعدة العملاء في عمليات تنظيم وفرز المنتجات', NULL, NULL),
(14, 13, 'en', 'self-adhesive-color-tape', 'Color Tape', 'Color tape is made coated with water based acrylic adhesive BOPP films , its can provided in many colors to help customers in a well-organized operations , also in sorting products in the warehouse .\r\nIt’s available in different sizes &amp; width to meet client’s special requirements .\r\nIt can be used in controlling products and sorting different types in warehouses .', 'Self Adhesive Tape | Self Adhesive Color Tape', 'Color tape is made coated with water based acrylic adhesive BOPP films , its can provided in many colors to help customers in a well-organized operations', NULL, NULL),
(15, 14, 'ar', 'الاشرطة-ذاتية-اللصق-المطبوعة', 'الاشرطة ذاتية اللصق المطبوعة', 'يعد استعدام الاشرطة ذاتية اللصق المطبوعة رائعًا لتغليف المنتجات كما انه يستخدم أيضًا كأداة تسويق فعالة منخفضة التكلفة.\r\nهناك العديد من المزايا المكتسبة من خلال استخدام الاشرطة ذاتية اللصق المطبوعة بصرف النظر عن مجرد اداة لتغليف الصناديق والطرود الخاصة بك بشكل آمن ، حيث يعمل التصميم المتسخدم كهوية بصرية تعزز علامتك التجارية أثناء النقل. إنه أيضًا منتج رائع لزيادة الوعي بعلامتك التجارية.', 'الاشرطة ذاتية اللصق | الاشرطة ذاتية اللصق المطبوعة', 'يعد استعدام الاشرطة ذاتية اللصق المطبوعة رائعًا لتغليف المنتجات كما انه يستخدم أيضًا كأداة تسويق فعالة منخفضة التكلفة.وهناك العديد من المزايا المكتسبة', NULL, NULL),
(16, 14, 'en', 'printed-self-adhesive-tape', 'Printed Self Adhesive Tape', 'Printed Self Adhesive Tape is great for sealing boxes and is also used as an effective low cost Marketing Tool. There are numerous advantages gained by utilizing a custom tape apart from just sealing your boxes securely, the continuous design acts as a visual tamper evident security measure and promotes your brand whilst in transit. It’s also a great product to increase your brand awareness.', 'Self Adhesive Tape | Printed Self Adhesive Tape', 'Printed Self Adhesive Tape is great for sealing boxes and is also used as an effective low cost Marketing Tool. There are numerous advantages', NULL, NULL),
(17, 15, 'ar', 'ألومنيوم-فويل', 'الألومنيوم فويل', 'رقائق الألومنيوم أو ورق الألومنيوم هو الألومنيوم مُعد بورق رقيق، بسماكة أقل من 0.2 مل، قد تصل في بعض الأحيان إلى سماكة 6 ميكرومتر، يستخدم لتغليف الأطعمة، إن هذه الرقاقات تكون مرنةً وبسهولة يمكن ثنيها وجعلها تلتف حول الأشياء، تكون الرقاقات بعض الأحيان هشةً لذلك يقام بتدعيمها بمواد أخرى كالبلاستيك والورق العادي لجعلها أكثر فائدة. في القرن العشرين حلت رقاقات الألمنيوم محل الرقاقات القصديرية.', 'عتمان جروب متخصصون فى صناعة ألومنيوم فويل', 'رقائق الألومنيوم أو ورق الألومنيوم هو الألومنيوم مُعد بورق رقيق، بسماكة أقل من 0.2 مل، قد تصل في بعض الأحيان إلى سماكة 6 ميكرومتر، يستخدم لتغليف الأطعمة', NULL, NULL),
(18, 15, 'en', 'aluminum-foil', 'Aluminum Foil', 'Aluminium foil is aluminium prepared in thin metal leaves with a thickness less than 0.2 mm thinner gauges down to 6 micrometres (0.24 mils) are also commonly used. The foil is pliable, and can be readily bent or wrapped around objects. Thin foils are fragile and are sometimes laminated with other materials such as plastics or paper to make them stronger and more useful.', 'Atman Group specializes in the manufacture of aluminum foil', 'Aluminium foil is aluminium prepared in thin metal leaves with a thickness less than 0.2 mm thinner gauges down to 6 micrometres (0.24 mils) are also commonly', NULL, NULL),
(19, 16, 'ar', 'الومنيوم-فويل-للاستخدام-الصناعى', 'الومنيوم فويل للاستخدام الصناعى', 'يعد العزل أحد أهم مجالات تطبيق رقائق الألومنيوم. يتم استخدامه على سبيل المثال كطبقة عازلة للحرارة لعزل الأنابيب والقنوات.\r\n\r\nبدأ ظهور رقائق الألومنيوم في صناعة التعبئة والتغليف في وقت مبكر من بداية القرن العشرين. في وقت مبكر من عام 1910 ، كان من الممكن إنتاج ما يصل إلى 10 ميكرولتر (1/100 مم) رقائق ألمنيوم سميكة وتصفيحها بالورق. أدت التحسينات التكنولوجية إلى تطور سريع من استخدام الألمنيوم لتغليف الشوكولاتة إلى تصنيع علب المشروبات ، وكبسولات القهوة ، وصواني الشواء وأغطية الزجاجات.', 'الألومنيوم فويل | الومنيوم فويل للاستخدام الصناعى', 'يعد العزل أحد أهم مجالات تطبيق رقائق الألومنيوم. يتم استخدامه على سبيل المثال كطبقة عازلة للحرارة لعزل الأنابيب والقنوات.', NULL, NULL),
(20, 16, 'en', 'aluminium-foil-for-industry-use', 'Aluminium foil for Industry Use', 'One of the most important fields of application of aluminum foil is insulation. It is used for example as a heat-insulating layer for the insulation of pipes and ducts.\r\n\r\nThe rise of aluminum foil in the packaging industry began as early as the beginning of the 20th century. As early as 1910, it was possible to produce up to 10 μ (1/100 mm) thick aluminum foils and laminate them with paper. Technological improvements have led to a rapid development from the use of aluminum as chocolate packaging to the manufacture of aluminum beverage cans, coffee capsules, grill trays and bottle caps.', 'Aluminium Foil | Aluminium foil for Industry Use', 'One of the most important fields of application of aluminum foil is insulation. It is used for example as a heat-insulating layer for the insulation of pipes', NULL, NULL),
(21, 17, 'ar', 'الومنيوم-فويل-استخدام-منزلى', 'الومنيوم فويل استخدام منزلى', 'مثالي لاحتياجات الطهي اليومية وسهولة التنظيف آمن للطعام وخالي من أي مواد ضارة.يمكننا توفير علامات تجارية مختلفة للمنتجات النهائية لتلبية متطلبات جميع العملاء.\r\nالاستخدامات للمنزل والمقهى والمطعم. يمكن استخدامها في تغليف الوجبات السريعة.\r\nاستخدم أيضًا في تطبيق الطهي لحماية سطح الفرن.', 'الومنيوم فويل | الومنيوم فويل استخدام منزلى', 'مثالي لاحتياجات الطهي اليومية وسهولة التنظيف غلاف رقائق الطعام آمن للطعام وخالي من أي مواد ضارة.يمكننا توفير علامات تجارية مختلفة للمنتجات', NULL, NULL),
(22, 17, 'en', 'aluminium-foil-for-house-hold', 'Aluminium foil for House Hold', 'Perfect for everyday cooking needs and easy clean up\r\nThe food grade foil wrap is food-safe, free of any harmful substances.\r\nwe can supply different brands for finished products to meet all clients requirement .\r\nUsages for house , cafe and restaurant . can use in fast food packing . \r\nAlso use in cook application for oven surface protection .', 'Aluminium Foil | Aluminium foil for House Hold', 'We can supply finish goods for aluminum foil for house and home use , as need in wrap food in homes.we can supply different brands for finished products to', NULL, NULL),
(23, 18, 'ar', 'food-and-beverage', 'الأغذية والمشروبات', 'صناعة الأغذية والمشروبات كبيرة ومتنوعة ومليئة بالآلات المتخصصة. إنها واحدة من أقدم الصناعات على هذا الكوكب ، لكنها لا تزال مليئة بالابتكار.\r\n\r\nواستجابةً لحاجة الصناعة إلى هذا التطور السريع ، واهتمامها المتزايد بسلامة الأغذية وأمنها ، نقدم الحلول التي تلبي هذه الاحتياجات الحالية.\r\n\r\nتوفر شركة عتمان جروب مجموعة كبيرة من المنتجات التى تستخدم فى مجال الأطعمة والمشروبات المعبأة في حياتنا اليومية. وتستخدم هذه المنتجات في حياتنا اليومية ويمكننا العثور عليها في كل مكان الآن.', 'عتمان جروب قسم المنتجات الخاصة بالأغذية والمشروبات', 'صناعة الأغذية والمشروبات كبيرة ومتنوعة ومليئة بالآلات المتخصصة. إنها واحدة من أقدم الصناعات على هذا الكوكب ، لكنها لا تزال مليئة بالابتكار.', NULL, NULL),
(24, 18, 'en', 'food-and-beverage', 'Food And Beverage', 'The Food and Beverage Industry is large, diverse, and full of specialized machinery. It’s one of the oldest industries on the planet, but still full of innovation. \r\n\r\nIn response to industry’s need to comply with regulations of all sorts, and an increasing concern for food safety and security, we provide the solutions that meet current needs.\r\n\r\nItems used in smart solution for packed food and beverage in our daily life .These items use in our daily life we can find them every where now a day .', 'Etman Group Food and Beverage Products Division', 'The Food and Beverage Industry is large, diverse, and full of specialized machinery. It’s one of the oldest industries on the planet, but still full', NULL, NULL),
(25, 19, 'ar', 'الاسترتش-الغذائى', 'الاسترتش الغذائى', 'إن أهم دور يلعبه الاسترتش الغذائى في تغليف المواد الغذائية هو الحماية والحفظ. يمكن أن يمنع الاسترتش الغذائى الطعام من الهلاك ، ويطيل عمره الافتراضي ، ويحافظ على جودة الطعام. يوفر الاسترتش الغذائى بشكل عام الحماية للأغذية من ثلاثة جوانب: المواد الكيميائية (الغازات والرطوبة والضوء) والبيولوجية (الكائنات الحية الدقيقة والحشرات والحيوانات) والفيزيائية (الأضرار الميكانيكية). بالإضافة إلى حماية الأغذية وحفظها ، يمكن للاسترتش الغذائى أيضًا أن يقلل من هدر الطعام ، ويسهل عمليات التوزيع', 'الاسترتش الغذائى يستخدم في تغليف المواد الغذائية بغرض الحماية والحفظ', 'إن أهم دور يلعبه الاسترتش الغذائى في تغليف المواد الغذائية بغرض الحماية والحفظ. يمكن أن يمنع الاسترتش الغذائى الطعام من الهلاك', NULL, NULL),
(26, 19, 'en', 'cling-warp', 'Cling Warp', 'The most important role Cling Warp plays in food packaging is protection and preservation. Cling Warp can prevent food from perishing, extend its shelf-life, and maintain the quality of food. Cling Warp generally provides protection for food from three aspects: chemical (gases, moisture, and light), biological (microorganisms, insects and animals), and physical (mechanical damage). In addition to food protection and preservation, Cling Warp can also reduce food waste, tag food information, ease the distribution processes, and increase product visibility and microwavability', 'Cling Warp is used in food packaging for the purpose of protection', 'The most important role Cling Warp plays in food packaging is protection and preservation. Cling Warp can prevent food from perishing', NULL, NULL),
(27, 23, 'ar', 'مستلزمات-الهدايا', 'مستلزمات الهدايا', 'الهدايا هي رمز للسعادة والاحتفال. إنها بمثابة إظهار لمشاعرنا ويمكن أن تكون لفتة ذات مغزى تجاه شخص نقدره.\r\nعتمان جروب تمتلك الخبرة الكافية لكى تكون هى الشركة الاولى فى توفير جميع المستلزمات الخاصة بتغليف الهداية بداية من ورق الهدايا مرورا بشنط الهدايا والكوريشة الخ', 'عتمان جروب قسم منتجات الخاصة بمستلزمات الهدايا', 'عتمان جروب تمتلك الخبرة الكافية لكى تكون هى الشركة الاولى فى توفير جميع المستلزمات الخاصة بتغليف الهداية بداية من ورق الهدايا مرورا بشنط الهدايا والكوريشة الخ', NULL, NULL),
(28, 23, 'en', 'decorative-strips', 'Gift Accessories', 'Gifts are a symbol of happiness and celebration. They act as a demonstration of our feelings and can be a meaningful gesture towards someone that we value. \r\n\r\nEtman Group has sufficient experience to be the first company in providing all the requirements for gift wrapping, starting from gift paper through gift bags and cores, etc.', 'Etman Group Products section for Decorative Strips', 'Etman Group has sufficient experience to be the first company in providing all the requirements for gift wrapping, starting from gift paper through gift bags', NULL, NULL),
(29, 24, 'ar', 'مستلزمات-الهدايا-شرائط-الزينة', 'شرائط الزينة', 'عتمان جروب لديها الجودة التي تبحث عنها. من خلال مجموعة كبيرة من الاختيارات ، يمكنك استكشاف تشكيلتنا من أفضل المنتجات. ابحث عن شرائط الزينة ستجد انها من اهم المنتجات الشائع استخدمها بصورة يومية\r\n\r\nعتمان جروب هي مصنع محترف ومصدر للشريط وتمتلك أكثر من 40 عامًا من الخبرة في مجال صناعة شرائط الزينة . مع توفر العمالة الماهرة والمواد الخام المنتجة ذاتيًا ، سيكون التسليم السريع والجودة المستقرة أمرًا سهلاً في شركتنا.\r\n\r\nلدينا تشكيلة كبيرة من منتجات شرائط الزينة ، يمكن استخدامها لتزيين أي منتج. لحفلات الزفاف ، والكريسماس ، وأعياد الميلاد ، والخطوبة ، وعيد الأم ، والتهاني ، وديكورات المهرجانات ، والحرف اليدوية ، والهدايا ، وإكسسوارات الألعاب ، إلخ.', 'مستلزمات الهدايا | منتجات شرائط الزينة بجميع انواعها', 'عتمان جروب هي مصنع محترف ومصدر للشريط وتمتلك أكثر من 40 عامًا من الخبرة في مجال صناعة شرائط الزينة . مع توفر العمالة الماهرة والمواد الخام المنتجة ذاتيًا', NULL, NULL),
(30, 24, 'en', 'gift-accessories-ribbon', 'Ribbon', 'Etman Group has the selection and quality you’re looking for. With a collection that includes ribbons in every material,  you can explore our assortment of top product. Find ribbons you’ll find an excuse to use every day ! \r\n\r\nEtman Group  is a professional factory manufacturer &amp; exporter of ribbon More than 40 years experience in handmade ribbon . With skilled workers and self-produced raw materials, fast delivery and stable quality is easy in our company. \r\n\r\nWe have more than styles of ribbon, It can be used for decoration of any product. For wedding, Christmas, Birthday, Engagement,Mother’s day, Congratulations, and other festival decoration, Handcraft, gift and premiums, packing ornament and toy’s accessories etc.', 'Gift Accessories Decorative ribbon products of all kinds', 'Etman Group is a professional factory manufacturer & exporter of ribbon More than 40 years experience in handmade ribbon .', NULL, NULL),
(31, 25, 'ar', 'ورق-الهدايا', 'ورق الهدايا', 'ورق الهدايا من المنتجات التى يجب الاحتفاظ به في منزلك لجميع احتياجات تغليف الهدايا - أو لف مجموعة متنوعة من العناصر. تم انتجها من خامات عالية الجدوة ، سميكة ولا يمكن تمزقها بسهولة. يمكن استخدامه لتزيين أي منتج. لحفلات الزفاف ، والكريسماس ، وأعياد الميلاد ، والخطوبة ، وعيد الأم ، والتهاني ، والديكورات الأخرى للمهرجانات ، والحرف اليدوية ، والهدايا والأقساط ، وزخرفة التعبئة ، وإكسسوارات الألعاب ، إلخ.', 'مستلزمات الهدايا | جميع منتجات ورق الهدايا من عتمان جروب ', 'ورق الهدايا من المنتجات التى يجب الاحتفاظ به في منزلك لجميع احتياجات تغليف الهدايا - أو لف مجموعة متنوعة من العناصر. تم انتجها من خامات عالية الجدوة ', NULL, NULL),
(32, 25, 'en', 'Gift-Accessories-Gift-Paper', 'Gift Paper', 'Gift Paper is a must-have to keep in your home for all your gift wrapping needs – use it for gift bags or wrapping a variety of items. Created with high-quality paper materials, thick and not easily tear or rip. Item came with shrink film to prevent wrapping paper from scratches and reduce dust.It can be used for decoration of any product. For wedding, Christmas, Birthday, Engagement,Mother’s day, Congratulations, and other festival decoration, Handcraft, gift and premiums, packing ornament and toy’s accessories etc.', 'Gift Accessories |  All gift paper products from Etman Group', 'Gift Paper is a must-have to keep in your home for all your gift wrapping needs use it for gift bags or wrapping a variety of items. Created with high-quality', NULL, NULL),
(33, 26, 'ar', 'مستلزمات-الهدايا-الكوريشة', 'الكوريشة', 'تستخدم ورق الكوريشة عالي الجودة الخاص بنا لإنشاء باقة زهور جميلة مثالي لحفلات الزفاف والذكرى السنوية واحتفالات أعياد الميلاد وحفلات التخرج وحفلات استقبال المولود الجديد وحفلات الخطوبة والمزيد!', 'مستلزمات الهدايا | جميع انواع منتجات الكوريشة المستوردة', 'تستخدم ورق الكوريشة عالي الجودة الخاص بنا لإنشاء باقة زهور جميلة مثالي لحفلات الزفاف والذكرى السنوية واحتفالات أعياد الميلاد وحفلات التخرج', NULL, NULL),
(34, 26, 'en', 'gift-accessories-crepe-paper', 'Crepe Paper', 'Premium Quality Crepe Paper Rolls,Crepe Paper flowers are a fabulous alternative to fresh flowers! Use our quality Crepe Paper to create a beautiful floral bouquet that will last for years to come. Perfect for weddings, anniversaries, birthday celebrations, graduations, baby showers, engagement parties, and more !', 'Gift Accessories | All type of imported Crepe Paper products', 'Premium Quality Crepe Paper Rolls,Crepe Paper flowers are a fabulous alternative to fresh flowers! Use our Crepe Paper to create a beautiful floral bouquet', NULL, NULL),
(35, 36, 'ar', 'الأشرطة-ذاتية-اللصق-ليزير-تيب', 'ليزير تيب', 'ليزير تيب يستخدام فى اعمال التغليف وكذلك فى الديكورات والاعمال الفنية و الحفلات وكذلك الاستخدامات المكتبية يمكننا توفير 6 ألوان مختلفة لتلبية طلب العميل.', 'الأشرطة ذاتية اللصق | ليزير تيب يستخدام فى اعمال التغليف والديكور', 'ليزير تيب يستخدام فى اعمال التغليف وكذلك فى الديكورات والاعمال الفنية و الحفلات وكذلك الاستخدامات المكتبية يمكننا توفير 6 ألوان مختلفة لتلبية طلب العميل.', NULL, NULL),
(36, 36, 'en', 'self-adhesive-tape-laser-tape', 'Laser Tape', 'Laser Tape use for sealing and decorative Use in parties and stationery we can supply 6 different colors to meet client request.', 'Self Adhesive Tape | LASER Tape Use in parties and stationery', 'Laser Tape use for sealing and decorative Use in parties and stationery we can supply 6 different colors to meet client request.', NULL, NULL),
(37, 37, 'ar', 'جامبو-رول', 'جامبو رول', 'شرائط BOPP الجامبو رول هي منتج نصف نهائى يستخدمه المصنعون للشرائط ذاتية اللصق عن طريق اعادة تقطيعه على الماكينات المجهزة لذلك مع منتجاتنا نضمن افضل جودة تساعدك على تقديم افضل منتج نهائى يستطيع المنافسة فى الاسواق المحلية والعالمية \r\n\r\nيمكننا توريد جميع أنواع الشرائط ذاتية اللصق BOPP بسماكات وألوان مختلفة ، عادي / مطبوع في رولات جامبو من جميع العروض والسمك.', 'الأشرطة ذاتية اللصق | جامبو رول | عتمان جروب', 'شرائط BOPP الجامبو رول هي منتج نصف نهائى يستخدمه المصنعون للشرائط ذاتية اللصق عن طريق اعادة تقطيعه على الماكينات المجهزة لذلك مع منتجاتنا نضمن افضل جودة', NULL, NULL),
(38, 37, 'en', 'jumbo-roll', 'Jumbo Roll', 'BOPP jumbo roll tape is Semi-finished product for Semi manufacturers slitting it into smaller rolls on the slitting machine. With our products, You can assure your brand quality stability.\r\n\r\nWe can supply all kinds of BOPP Self adhesive tape in various thicknesses, colors, plain/printed in Jumbo rolls of all widths and thickness.', 'Jumbo Roll | Self Adhesive Tape | Etman Group', 'BOPP jumbo roll tape is Semi-finished product for Semi manufacturers slitting it into smaller rolls on the slitting machine.We can supply all kinds of BOPP', NULL, NULL),
(39, 38, 'ar', 'ادوات-مكتبية', 'ادوات مكتبية', 'ادوات مكتبية', 'ادوات مكتبية', 'ادوات مكتبية', NULL, NULL),
(40, 38, 'en', 'stationary', 'Stationary', 'Stationary', 'Stationary', 'Stationary', NULL, NULL),
(41, 39, 'ar', 'مسدسات-الشمع', 'مسدسات الشمع', 'مسدسات الشمع', 'مسدسات الشمع', 'مسدسات الشمع', NULL, NULL),
(42, 39, 'en', 'glue-gun', 'Glue Gun', 'Glue Gun', 'Glue Gun', 'Glue Gun', NULL, NULL),
(43, 40, 'ar', 'اكواب-ورقيه', 'اكواب ورقيه', 'اكواب ورقيه', 'اكواب ورقيه', 'اكواب ورقيه', NULL, NULL),
(44, 40, 'en', 'paper-cups', 'Paper Cups', 'Paper Cups', 'Paper Cups', 'Paper Cups', NULL, NULL),
(45, 41, 'ar', 'استيك-نقدية', 'استيك نقدية', 'استيك نقدية', 'استيك نقدية', 'استيك نقدية', NULL, NULL),
(46, 41, 'en', 'cash-stick', 'Cash stick', 'Cash stick', 'Cash stick', 'Cash stick', NULL, NULL),
(47, 42, 'ar', 'مستلزمات-أعياد-ميلاد', 'مستلزمات أعياد ميلاد', 'مستلزمات أعياد ميلاد', 'مستلزمات أعياد ميلاد', 'مستلزمات أعياد ميلاد', NULL, NULL),
(48, 42, 'en', 'birthday-supplies', 'Birthday supplies', 'Birthday supplies', 'Birthday supplies', 'Birthday supplies', NULL, NULL),
(49, 43, 'ar', 'ورق-تصوير', 'ورق تصوير', 'ورق تصوير', 'ورق تصوير', 'ورق تصوير', NULL, NULL),
(50, 43, 'en', 'photocopy-paper', 'Photocopy paper', 'Photocopy paper', 'Photocopy paper', 'Photocopy paper', NULL, NULL),
(51, 44, 'ar', 'اسلحة-الكتر', 'اسلحة الكتر', 'اسلحة الكتر', 'اسلحة الكتر', 'اسلحة الكتر', NULL, NULL),
(52, 44, 'en', 'cutter', 'Cutter', 'Cutter', 'Cutter', 'Cutter', NULL, NULL),
(53, 45, 'ar', 'اطباق-بلاستيك', 'اطباق بلاستيك', 'اطباق بلاستيك', 'اطباق بلاستيك', 'اطباق بلاستيك', NULL, NULL),
(54, 45, 'en', 'plastic-dishes', 'Plastic dishes', 'Plastic dishes', 'Plastic dishes', 'Plastic dishes', NULL, NULL);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
