-- phpMyAdmin SQL Dump
-- version 5.2.0
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Sep 22, 2023 at 05:54 PM
-- Server version: 10.4.25-MariaDB
-- PHP Version: 8.1.10

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `a_etman`
--

--
-- Dumping data for table `product_translations`
--

INSERT INTO `product_translations` (`id`, `product_id`, `locale`, `slug`, `name`, `des`, `g_title`, `g_des`) VALUES
(1, 1, 'ar', 'شرائط-التعبئة-والتغليف-نار-تيب', 'نار تيب', 'نار تيب شرائط ذاتية اللصق مصنوع من مادة لاصقة ذات أساس مذيب مطلية على فيلم BOPP ، وهي متوفرة في فيلم شفاف ويمكن أيضًا توفيره في فيلم قاطم . هذا النوع يلبي متطلبات العميل من تغليف الكرتون التى يمكن وضعه في الثلاجات والافران. وهو مصنوع لدعم الظروف الخاصة بدرجة حرارة منخفضة أو عالية.', 'الأشرطة ذاتية اللصق | شرائط التعبئة والتغليف | نار تيب', 'نار تيب شرائط ذاتية اللصق مصنوع من مادة لاصقة ذات أساس مذيب مطلية على فيلم BOPP ، وهي متوفرة في فيلم شفاف ويمكن أيضًا توفيره في فيلم قاطم .'),
(2, 1, 'en', 'packaging-tape-nar-tape', 'Nar Tape', 'The Nar Tape is made from solvent based adhesive coated on BOPP film .It provide in clear film and also can supply in tan film .This type to meet client\'s requirement of packing carton which can go in fridge and oven .It made to support special circumstances as low or high temperature .', 'Self Adhesive Tape | Packaging Tape | Nar Tape', 'The Nar Tape is made from solvent based adhesive coated on BOPP film .It provide in clear film and also can supply in tan film .This type to meet client\'s'),
(3, 2, 'ar', 'شرائط-التعبئة-والتغليف-ذا-بيست-تيب', 'ذا بيست تيب', 'ذا بيست تيب شرائط ذاتية اللصق مصنوعة من مادة لاصقة ذات أساس مائي مطلية بفيلم BOPP ، وهي متوفرة في فيلم شفاف كريستالي ، وهذا النوع يلبي متطلبات العميل من تعبئة الكراتين بأسلوب يدعم الوزن العالي للكرتون.', 'الأشرطة ذاتية اللصق | شرائط التعبئة والتغليف | ذا بيست تيب', 'ذا بيست تيب شرائط ذاتية اللصق مصنوعة من مادة لاصقة ذات أساس مائي مطلية بفيلم BOPP ، وهي متوفرة في فيلم شفاف كريستالي'),
(4, 2, 'en', 'packaging-tape-the-best-tape', 'The Best Tape', 'The Best Tape is made from water based adhesive coated on BOPP film .\r\nIt provide in crystal clear film.This type to meet client\'s requirement of packing cartons with style and it support high weight of cartons .', 'Self Adhesive Tape | Packaging Tape | The Best Tape', 'The Best Tape is made from water based adhesive coated on BOPP film. It provide in crystal clear film.This type to meet client\'s requirement of packing'),
(5, 3, 'ar', 'شرائط-التعبئة-والتغليف-كريستال-تيب', 'كريستال تيب', 'كريستال تيب شرائط ذاتية اللصق مصنوعة من مادة لاصقة ذات أساس مائي مطلية بفيلم BOPP ، وهي متوفرة في فيلم شفاف كريستالي ، وهذا النوع يلبي متطلبات العميل من تعبئة الكراتين بأسلوب يدعم الوزن العالي للكرتون.', 'الأشرطة ذاتية اللصق | شرائط التعبئة والتغليف | كريستال تيب', 'كريستال تيب شرائط ذاتية اللصق مصنوعة من مادة لاصقة ذات أساس مائي مطلية بفيلم BOPP ، وهي متوفرة في فيلم شفاف كريستالي'),
(6, 3, 'en', 'packaging-tape-crystal-tape', 'Crystal Tape', 'The Crystal Tape  is made from water based adhesive coated on BOPP film .\r\nIt provide in crystal clear film.This type to meet client\'s requirement of packing cartons with style and it support high weight of cartons .', 'Self Adhesive Tape | Packaging Tape | Crystal Tape', 'The Crystal Tape  is made from water based adhesive coated on BOPP film .It provide in crystal clear film.This type to meet client\'s requirement of packing'),
(7, 4, 'ar', 'شرائط-التعبئة-والتغليف-جرين-تيب', 'جرين تيب', 'جرين تيب شرائط ذاتية اللصق مصنوعة من مادة لاصقة ذات أساس مائي مطلية بفيلم BOPP ، وهي متوفرة في فيلم شفاف كريستالي ، وهذا النوع يلبي متطلبات العميل من تعبئة الكراتين بأسلوب يدعم الوزن العالي للكرتون.', 'الأشرطة ذاتية اللصق | شرائط التعبئة والتغليف | جرين تيب', 'جرين تيب شرائط ذاتية اللصق مصنوعة من مادة لاصقة ذات أساس مائي مطلية بفيلم BOPP ، وهي متوفرة في فيلم شفاف كريستالي ، وهذا النوع يلبي متطلبات العميل من تعبئة'),
(8, 4, 'en', 'packaging-tape-green-tape', 'Green Tape', 'The Green Tape is made from water based adhesive coated on BOPP film .\r\nIt provide in crystal clear film.This type to meet client\'s requirement of packing cartons with style and it support high weight of cartons .', 'Self Adhesive Tape | Packaging Tape | Green Tape', 'The Green Tape is made from water based adhesive coated on BOPP film .It provide in crystal clear film.This type to meet client\'s requirement'),
(9, 7, 'ar', 'السوليتب-المكتبى-ذا-بيست', 'ذا بيست', 'سوليتب مكتبى ذا بيست مصنوع من مادة لاصقة أكريليك مائيّة مطلية بأفلام BOOP وهي متوفرة بأحجام وعرض مختلفة. الاستعمال: تغليف الهدايا ، التعبئة الخفيفة ، الأعمال الفنية ، التطبيقات المكتبية ، إصلاح الورق وتقوية المستندات.', 'الأشرطة ذاتية اللصق | السوليتب المكتبى | ذا بيست', 'سوليتب مكتبى ذا بيست مصنوع من مادة لاصقة أكريليك مائيّة مطلية بأفلام BOOP وهي متوفرة بأحجام وعرض مختلفة. الاستعمال: تغليف الهدايا ، التعبئة الخفيفة'),
(10, 7, 'en', 'stationary-tape-the-best', 'The Best', 'The Best Stationary tape is made with water based acrylic adhesive coated on BOOP films It available with different sizes and widths. Usage : gift wrapping , light packing , art craft , office application , paper mending and reinforcing documents .', 'Self Adhesive Tape | Stationary Tape | The Best', 'The Best Stationary tape is made with water based acrylic adhesive coated on BOOP films It available with different sizes and widths. Usage gift wrapping'),
(11, 9, 'ar', 'الأشرطة-ذاتية-اللصق-جرين-ماسك-تيب', 'جرين ماسك تيب', 'جرين ماسك تيب مصنوع من خامات ورقية مغطى بمادة لاصقة مطاطية يمكن استخدامها في تطبيقات الحماية والتثبيت والأغراض العامة. إنه متوفر بأحجام مختلفة لتلبية متطلبات العميل الخاصة. تستخدم بدرجات حرارة مختلفة للدهان السيارات. وتغطية الأسطح أثناء الرش أو الطلاء. وكذلك حماية الأسطح المعدنية والبلاستيكية والزجاجية.', 'الأشرطة ذاتية اللصق | جرين ماسك تيب', 'جرين ماسك تيب مصنوع من خامات ورقية مغطى بمادة لاصقة مطاطية يمكن استخدامها في تطبيقات الحماية والتثبيت والأغراض العامة. إنه متوفر بأحجام مختلفة'),
(12, 9, 'en', 'self-adhesive-tape-green-masking-tape', 'Green Masking Tape', 'Green Masking Tape is made of crepe paper that coated with rubber adhesive that could use for sealing , holding and general purpose applications. It’s available in different sizes , widths and designs to meet client’s special requirements. It used in different temperature degrees for painting and car’s spray. and Covering surfaces during spraying or painting. and also Protection of metal , plastic and glasses surfaces .', 'Self Adhesive Tape | Green Masking Tape', 'Green Masking Tape is made of crepe paper that coated with rubber adhesive that could use for sealing , holding and general purpose applications.'),
(13, 10, 'ar', 'الأشرطة-ذاتية-اللصق-اى-تى-ماسك-تيب', 'اى تى ماسك تيب', 'اى تى ماسك تيب مصنوع من خامات ورقية مغطى بمادة لاصقة مطاطية يمكن استخدامها في تطبيقات الحماية والتثبيت والأغراض العامة. إنه متوفر بأحجام مختلفة لتلبية متطلبات العميل الخاصة. تستخدم بدرجات حرارة مختلفة للدهان السيارات. وتغطية الأسطح أثناء الرش أو الطلاء. وكذلك حماية الأسطح المعدنية والبلاستيكية والزجاجية.', 'الأشرطة ذاتية اللصق | اى تى ماسك تيب', 'اى تى ماسك تيب مصنوع من خامات ورقية مغطى بمادة لاصقة مطاطية يمكن استخدامها في تطبيقات الحماية والتثبيت والأغراض العامة. إنه متوفر بأحجام مختلفة'),
(14, 10, 'en', 'self-adhesive-tape-et-masking-tape', 'ET Masking Tape', 'ET Masking Tape is made of crepe paper that coated with rubber adhesive that could use for sealing , holding and general purpose applications. It’s available in different sizes , widths and designs to meet client’s special requirements. It used in different temperature degrees for painting and car’s spray. and Covering surfaces during spraying or painting. and also Protection of metal , plastic and glasses surfaces .', 'Self Adhesive Tape | ET Masking Tape', 'ET Masking Tape is made of crepe paper that coated with rubber adhesive that could use for sealing , holding and general purpose applications. It’s available'),
(15, 12, 'ar', 'الاشرطة-ذاتية-اللصق-المطبوعة-فريش', 'فريش', 'فريش شريط لاصق مطبوع مصنوع من مادة لاصقة أكريليك مائية مطلية بأفلام BOPP .إنه مصنوع من أفضل المواد والخامات لتلبية متطلبات المستخدمين النهائيين. يمكن استخدامه في تغليف المنتجات التي توضح الأصل المصري للمحتوى.', 'الأشرطة ذاتية اللصق | الاشرطة ذاتية اللصق المطبوعة | فريش', 'فريش المطبوع مصنوع من مادة لاصقة أكريليك مائية مطلية بأفلام BOPP .إنه مصنوع من أفضل المواد والخامات لتلبية متطلبات المستخدمين النهائيين.'),
(16, 12, 'en', 'printed-self-adhesive-tape-fresh', 'Fresh printed tape', 'Fresh printed tape is made with water based acrylic adhesive coated on BOPP films its made for best materials to meet end users requirements . it can use in sealing some thing showing the Egyptian origin of the content .', 'Self Adhesive Tape | Printed Self Adhesive Tape | Fresh', 'Fresh printed tape is made with water based acrylic adhesive coated on BOPP films its made for best materials to meet end users requirements'),
(17, 13, 'ar', 'الاشرطة-ذاتية-اللصق-المطبوعة-قابل-للكسر', 'قابل للكسر', 'قابل للكسر شريط لاصق مطبوع مصنوع من مادة لاصقة أكريليك مائية مطلية بأفلام BOPP .إنه مصنوع من أفضل المواد والخامات لتلبية متطلبات المستخدمين النهائيين.يمكن استخدامه في تغليف المنتجات القابلة للكسر للحفاظ على سلامة اثناء عمليات التخزين والنقل', 'الأشرطة ذاتية اللصق | الاشرطة ذاتية اللصق المطبوعة | قابل للكسر', 'قابل للكسر شريط لاصق مطبوع مصنوع من مادة لاصقة أكريليك مائية مطلية بأفلام BOPP .إنه مصنوع من أفضل المواد والخامات لتلبية متطلبات المستخدمين'),
(18, 13, 'en', 'fragile-printed-tape', 'Fragile printed tape', 'Fragile printed tape its made for best materials to meet end users requirements . \r\nit can use in sealing some thing to be caution to avoid any misunderstanding to save products .', 'Self Adhesive Tape | Printed Self Adhesive Tape | Fragile tape', 'Fragile printed tape its made for best materials to meet end users requirements\r\nit can use in sealing some thing to be caution to avoid any misunderstanding'),
(19, 14, 'ar', 'الأشرطة-ذاتية-اللصق-شريط-العزل-الكهربائي-et', 'شرائط العزل الكهربائي ET', 'شرائط العزل الكهربائي PVC مصنوعة من البولي فينيل كلوريد (spvc) المطلي بمادة لاصقة حساسة للضغط، كما أنه يعتبر مقاومًا جيدًا لدرجات الحرارة والرطوبة والجهد العالي وتطبيقات الحماية. متوفر بأحجام مختلفة. يستخدم فى تطبيقات الاعمال الكهربائية', 'الأشرطة ذاتية اللصق | شريط العزل الكهربائي ET', 'شرائط العزل الكهربائي PVC مصنوعة من افضل خامات تايوان ذات الأداء العالي والجودة في استخدام التطبيق.'),
(20, 14, 'en', 'self-adhesive-tape-electrical-insulating-tape', 'PVC Electrical Tape - ET', 'Electrical Insulating Tape PVC insulating tape is made from soft polyvinyl chloride (spvc) which is coated with rubber pressure -sensitive adhesive , it’s also considered good resistant to temperature , moisture , high voltage and protection applications .\r\nPVC electrical tape made from the best TAIWAN materials with high performance and quality can feel in application use .\r\nIt’s available in different sizes .Usage in Strong tensile strength use in electric work application .', 'Self Adhesive Tape | Electrical Insulating Tape', 'PVC electrical tape made from the best TAIWAN materials with high performance and quality can feel in application use .'),
(21, 15, 'ar', 'الومنيوم-فويل-مستر-فويل-50-جرام', 'الومنيوم فويل مستر فويل 50 جرام', 'العلامة التجارية رقم 1 لرقائق الألمنيوم المصنوعة في مصر ، مستر فويل بالقوة والجودة الموثوق بها التي يمكنك الاعتماد عليها لطهي وجبات لذيذة مع سهولة التنظيف\r\nسميكة جدًا للطبخ في الفرن أو على الشواية أو على النار ؛ يسمح للطهي لفترة أطول من أجل شواء اللحوم بشكل أفضل.يساعدك صندوق الورق المقوى المزود بقاطع معدني على تمزيق ورق القصدير بشكل أكثر كفاءة وراحة.', 'الومنيوم فويل استخدام منزلى | الومنيوم فويل مستر فويل 50 جرام', 'العلامة التجارية رقم 1 لرقائق الألمنيوم المصنوعة في مصر ، مستر فويل بالقوة والجودة الموثوق بها التي يمكنك الاعتماد عليها لطهي وجبات'),
(22, 15, 'en', 'aluminium-foil-mr-foil-50gm', 'Aluminium foil MR. FOIL', 'The number 1 brand of aluminum foil made in the Egypt, MR. FOIL has the trusted strength and quality you can count on for cooking delicious meals with easy cleanup \r\nExtra thickened for cooking in the oven, on the grill or over a fire; allows for longer cooking limiting to better broil the meats.\r\nPaper board box with metal cutter help you to tear off the foil paper more efficiently and conveniently.', 'Aluminium foil for House Hold | Aluminium foil MR. FOIL 50gm', 'The number 1 brand of aluminum foil made in the Egypt, MR. FOIL has the trusted strength and quality you can count on for cooking delicious meals'),
(23, 16, 'ar', 'مستلزمات-الهدايا-شرائط-الزينة-نصف-سم', 'شرائط الزينة ½ سم', 'شرائط الزينة ½ سم مصنوع من مادة البولي بروبيلين عالية الجودة ومتوفر بعدة ألوان. يمكن استخدامها لتزيين أي منتج. لحفلات الزفاف ، والكريسماس ، وأعياد الميلاد ، والخطوبة ، وعيد الأم ، والتهاني ، وديكورات المهرجانات ، والحرف اليدوية ، والهدايا ، وإكسسوارات الألعاب ، إلخ.', 'مستلزمات الهدايا | شرائط الزينة | شرائط الزينة ½ سم', 'شرائط الزينة ½ سم مصنوع من مادة البولي بروبيلين عالية الجودة ومتوفر بعدة ألوان. يمكن استخدامها لتزيين أي منتج. لحفلات الزفاف ، والكريسماس ، وأعياد الميلاد'),
(24, 16, 'en', 'gift-accessories-05-cm-pp-ribbon', '½ Cm PP Ribbon', '½ cm PP ribbon It is made of quality polypropylene material and is available in several colors. It can be used for decoration of any product. For wedding, Christmas, Birthday, Engagement,Mother’s day, Congratulations, and other festival decoration, Handcraft, gift and premiums, packing ornament and toy’s accessories etc.', 'Gift Accessories | Ribbon | ½ cm PP ribbon', '½ cm PP ribbon It is made of quality polypropylene material and is available in several colors. It can be used for decoration of any product. For wedding'),
(25, 17, 'ar', 'مستلزمات-الهدايا-شرائط-الزينة-5-سم', 'شرائط الزينة 5 سم', 'شرائط الزينة 5 سم مصنوع من مادة البولي بروبيلين عالية الجودة ومتوفر بعدة ألوان. يمكن استخدامها لتزيين أي منتج. لحفلات الزفاف ، والكريسماس ، وأعياد الميلاد ، والخطوبة ، وعيد الأم ، والتهاني ، وديكورات المهرجانات ، والحرف اليدوية ، والهدايا ، وإكسسوارات الألعاب ، إلخ.', 'مستلزمات الهدايا | شرائط الزينة | شرائط الزينة 5 سم', 'شرائط الزينة 5 سم مصنوع من مادة البولي بروبيلين عالية الجودة ومتوفر بعدة ألوان. يمكن استخدامها لتزيين أي منتج. لحفلات الزفاف ، والكريسماس ، وأعياد الميلاد'),
(26, 17, 'en', 'gift-accessories-5-cm-pp-ribbon', '5 Cm PP Ribbon', '5 Cm PP Ribbon It is made of quality polypropylene material and is available in several colors. It can be used for decoration of any product. For wedding, Christmas, Birthday, Engagement,Mother’s day, Congratulations, and other festival decoration, Handcraft, gift and premiums, packing ornament and toy’s accessories etc.', 'Gift Accessories | Ribbon | 5 cm PP ribbon', '5 cm PP ribbon It is made of quality polypropylene material and is available in several colors. It can be used for decoration of any product. For wedding'),
(27, 18, 'ar', 'مستلزمات-الهدايا-شرائط-الزينة-الميتاليكا', 'شرائط الزينة الميتاليكا', 'شرائط الزينة الميتاليكا مصنوع من مادة البولي بروبيلين عالية الجودة ومتوفر بعدة ألوان. يمكن استخدامها لتزيين أي منتج. لحفلات الزفاف ، والكريسماس ، وأعياد الميلاد ، والخطوبة ، وعيد الأم ، والتهاني ، وديكورات المهرجانات ، والحرف اليدوية ، والهدايا ، وإكسسوارات الألعاب ، إلخ.', 'مستلزمات الهدايا | شرائط الزينة | شرائط الزينة الميتاليكا', 'شرائط الزينة الميتاليكا مصنوع من مادة البولي بروبيلين عالية الجودة ومتوفر بعدة ألوان. يمكن استخدامها لتزيين أي منتج. لحفلات الزفاف ، والكريسماس , أعياد الميلاد'),
(28, 18, 'en', 'gift-accessories-metallic-pp-ribbon', 'Metallic PP Ribbon', 'Metallic PP ribbon It is made of quality polypropylene material and is available in several colors. It can be used for decoration of any product. For wedding, Christmas, Birthday, Engagement,Mother’s day, Congratulations, and other festival decoration, Handcraft, gift and premiums, packing ornament and toy’s accessories etc.', 'Gift Accessories | Ribbon | Metallic PP ribbon', 'Metallic PP ribbon It is made of quality polypropylene material and is available in several colors. It can be used for decoration of any product. For wedding'),
(29, 19, 'ar', 'مستلزمات-الهدايا-ورق-لف-الهدايا-الميتلك', 'ورق لف الهدايا الميتلك', 'يأتي ورق لف الهدايا بمجموعة كبيرة من التصميمات الابداعية ، ورق تغليف الهدايا المعدني المطبوع هو عنصر مثالي لتغليف الهدايا بمجموعة كبيرة من التصاميم والأنماط التي تغطي اذواق الأطفال والبنات والأولاد والاذواق العالمية و أعيد الميلاد وتضفي لمسة نهائية رائعة على هداياك.', 'مستلزمات الهدايا | ورق لف الهدايا | ورق لف الهدايا الميتلك', 'ورق لف الهدايا الميتلك يأتي بمجموعة كبيرة من التصميمات الابداعية ، ورق تغليف الهدايا المعدني المطبوع هو عنصر مثالي لتغليف الهدايا بمجموعة كبيرة'),
(30, 19, 'en', 'gift-accessories-metallic-paper', 'Metallic Paper', 'Metallic Paper come with Creative designs printed metallized gift wrap is prefect item to wrap gifts. Large ranges of designs and patterns covering baby, girls, boys, universal patterns and Christmas for your selection and give incredible finish to your gifts.', 'Gift Accessories | Gift Paper | Metallic paper', 'Metallic Paper come with Creative designs printed metallized gift wrap is prefect item to wrap gifts. Large ranges of designs and patterns covering baby, girls'),
(31, 21, 'ar', 'مستلزمات-الهدايا-ورق-كوريشة', 'ورق كوريشة', 'تستخدم ورق الكوريشة عالي الجودة الخاص بنا لإنشاء باقة زهور جميلة مثالي لحفلات الزفاف والذكرى السنوية واحتفالات أعياد الميلاد وحفلات التخرج وحفلات استقبال المولود الجديد وحفلات الخطوبة والمزيد!', 'مستلزمات الهدايا | ورق الكوريشة | ورق كوريشة', 'تستخدم ورق الكوريشة عالي الجودة الخاص بنا لإنشاء باقة زهور جميلة مثالي لحفلات الزفاف والذكرى السنوية واحتفالات أعياد الميلاد وحفلات التخرج'),
(32, 21, 'en', 'crepe-paper-normal-color', 'Normal Color', 'Crepe Paper Normal Color are a fabulous alternative to fresh flowers! Use our quality Crepe Paper to create a beautiful floral bouquet that will last for years to come. Perfect for weddings, anniversaries, birthday celebrations, graduations, baby showers, engagement parties, and more', 'Gift Accessories | Crepe Paper Normal Color', 'Crepe Paper Normal Color are a fabulous alternative to fresh flowers! Use our quality Crepe Paper to create a beautiful floral bouquet'),
(33, 22, 'ar', 'مستلزمات-الهدايا-ورق-كوريشة-ميتاليك', 'ورق كوريشة ميتاليك', 'تستخدم ورق الكوريشة الميتاليك عالي الجودة الخاص بنا لإنشاء باقة زهور جميلة مثالي لحفلات الزفاف والذكرى السنوية واحتفالات أعياد الميلاد وحفلات التخرج وحفلات استقبال المولود الجديد وحفلات الخطوبة والمزيد!', 'مستلزمات الهدايا | ورق كوريشة | ورق كوريشة ميتاليك', 'تستخدم ورق الكوريشة الميتاليك عالي الجودة الخاص بنا لإنشاء باقة زهور جميلة مثالي لحفلات الزفاف والذكرى السنوية واحتفالات أعياد الميلاد وحفلات التخرج'),
(34, 22, 'en', 'crepe-paper-metallic-color', 'Metallic Color', 'Crepe Paper Metallic Color are a fabulous alternative to fresh flowers! Use our quality Crepe Paper to create a beautiful floral bouquet that will last for years to come. Perfect for weddings, anniversaries, birthday celebrations, graduations, baby showers, engagement parties, and more', 'Gift Accessories | Crepe Paper Metallic color', 'Crepe Paper Metallic Color are a fabulous alternative to fresh flowers! Use our quality Crepe Paper to create a beautiful floral bouquet'),
(35, 37, 'ar', 'شرائط-التعبئة-والتغليف-ابل-تيب', 'ابل تيب', 'ابل تيب شرائط ذاتية اللصق مصنوعة من مادة لاصقة ذات أساس مائي مطلية بفيلم BOPP ، وهي متوفرة في فيلم شفاف كريستالي ، وهذا النوع يلبي متطلبات العميل من تعبئة الكراتين بأسلوب يدعم الوزن العالي للكرتون.', 'الأشرطة ذاتية اللصق | شرائط التعبئة والتغليف | ابل تيب', 'ابل تيب شرائط ذاتية اللصق مصنوعة من مادة لاصقة ذات أساس مائي مطلية بفيلم BOPP ، وهي متوفرة في فيلم شفاف كريستالي وهذا النوع يلبي متطلبات العميل'),
(36, 37, 'en', 'packaging-tape-apple-tape', 'Apple Tape', 'The Apple Tape is made from water based adhesive coated on BOPP film .\r\nIt provide in crystal clear film.This type to meet client\'s requirement of packing cartons with style and it support high weight of cartons .', 'Self Adhesive Tape | Packaging Tape | Apple Tape', 'The Apple Tape is made from water based adhesive coated on BOPP film.It provide in crystal clear film.This type to meet client\'s requirement of packing'),
(37, 38, 'ar', 'شرائط-التعبئة-والتغليف-فاير-تيب', 'فاير تيب', 'فاير تيب شرائط ذاتية اللصق مصنوعة من مادة لاصقة ذات أساس مائي مطلية بفيلم BOPP ، وهي متوفرة في فيلم شفاف كريستالي ، وهذا النوع يلبي متطلبات العميل من تعبئة الكراتين بأسلوب يدعم الوزن العالي للكرتون.', 'الأشرطة ذاتية اللصق | شرائط التعبئة والتغليف | فاير تيب', 'فاير تيب شرائط ذاتية اللصق مصنوعة من مادة لاصقة ذات أساس مائي مطلية بفيلم BOPP ، وهي متوفرة في فيلم شفاف كريستالي ، وهذا النوع يلبي متطلبات العميل من تعبئة'),
(38, 38, 'en', 'packaging-tape-fire-tape', 'Fire Tape', 'The Frie tape is made from water based adhesive coated on BOPP film .\r\nIt provide in crystal clear film.This type to meet client\'s requirement of packing cartons with style and it support high weight of cartons .', 'Self Adhesive Tape | Packaging Tape | Fire Tape', 'The Frie tape is made from water based adhesive coated on BOPP film .It provide in crystal clear film.This type to meet client\'s requirement of packing carton'),
(39, 40, 'ar', 'شرائط-ذاتية-اللصق-ملونه-هوت-تيب', 'هوت تيب', 'الشرائط ذاتية اللصق الملونه هوت مصنوعه من أغشية BOPP اللاصقة المائية المصنوعة من الأكريليك ، ويمكن توفيره بألوان عديدة لمساعدة العملاء في عمليات تنظيم وفرز المنتجات اثناء التخزين او النقل متوفر بأحجام وعرض مختلفة لتلبية جميع احتياجات و متطلبات العملاء الخاصة', 'الأشرطة ذاتية اللصق | شرائط ذاتية اللصق ملونه | هوت تيب', 'الشرائط ذاتية اللصق الملونه هوت مصنوعه من أغشية BOPP اللاصقة المائية المصنوعة من الأكريليك ، ويمكن توفيره بألوان عديدة لمساعدة العملاء في عمليات تنظيم وفرز'),
(40, 40, 'en', 'self-adhesive-color-tape-hot', 'Hot', 'HOT Self Adhesive Color Tape is made coated with water based acrylic adhesive BOPP films , its can provided in many colors to help customers in a well-organized operations , also in sorting products in the warehouse .\r\nIt’s available in different sizes & width to meet client’s special requirements .', 'Self Adhesive Tape | Self Adhesive Color Tape | Hot Tape', 'HOT Self Adhesive Color Tape made coated with water based acrylic adhesive BOPP films , its can provided in many colors to help customers in a well-organized'),
(41, 41, 'ar', 'الأشرطة-ذاتية-اللصق-جرين-ليزير-تيب', 'جرين تيب', 'جرين ليزير تيب يستخدام فى اعمال التغليف وكذلك فى الديكورات والاعمال الفنية و الحفلات وكذلك الاستخدامات المكتبية يمكننا توفير 6 ألوان مختلفة لتلبية طلب العميل.', 'الأشرطة ذاتية اللصق | جرين ليزير تيب', 'جرين ليزير تيب يستخدام فى اعمال التغليف وكذلك فى الديكورات والاعمال الفنية و الحفلات وكذلك الاستخدامات المكتبية يمكننا توفير 6 ألوان مختلفة لتلبية طلب العميل.'),
(42, 41, 'en', 'self-adhesive-tape-green-laser-tape', 'Green Tape', 'Green Laser Tape use for sealing and decorative Use in parties and stationery we can supply 6 different colors to meet client request.', 'Self Adhesive Tape | Green Laser Tape', 'Green Laser Tape use for sealing and decorative Use in parties and stationery we can supply 6 different colors to meet client request.'),
(43, 42, 'ar', 'السوليتب-المكتبى-بيتون-تيب', 'بيتون تيب', 'سوليتب مكتبى بيتون تيب مصنوع من مادة لاصقة أكريليك مائيّة مطلية بأفلام BOOP وهي متوفرة بأحجام وعرض مختلفة. الاستعمال: تغليف الهدايا ، التعبئة الخفيفة ، الأعمال الفنية ، التطبيقات المكتبية ، إصلاح الورق وتقوية المستندات.', 'الأشرطة ذاتية اللصق | السوليتب المكتبى | بيتون تيب', 'سوليتب مكتبى بيتون تيب مصنوع من مادة لاصقة أكريليك مائيّة مطلية بأفلام BOOP وهي متوفرة بأحجام وعرض مختلفة. الاستعمال: تغليف الهدايا'),
(44, 42, 'en', 'stationary-tape-piton-tape', 'PITON', 'The PITON Stationary tape is made with water based acrylic adhesive coated on BOOP films It available with different sizes and widths. Usage : gift wrapping , light packing , art craft , office application , paper mending and reinforcing documents .', 'Self Adhesive Tape | Stationary Tape | PITON Tape', 'The PITON Stationary tape is made with water based acrylic adhesive coated on BOOP films It available with different sizes and widths. Usage : gift wrapping'),
(45, 43, 'ar', 'السوليتب-المكتبى-سوليتب-مكتبى-ملون', 'سوليتب مكتبى ملون', 'السوليتب المكتبى الملون مصنوع من مادة لاصقة أكريليك مائيّة مطلية بأفلام BOOP وهي متوفرة بأحجام وعرض مختلفة. الاستعمال: تغليف الهدايا ، التعبئة الخفيفة ، الأعمال الفنية ، التطبيقات المكتبية ، إصلاح الورق وتقوية المستندات.', 'الأشرطة ذاتية اللصق | السوليتب المكتبى | سوليتب مكتبى ملون', 'السوليتب المكتبى الملون مصنوع من مادة لاصقة أكريليك مائيّة مطلية بأفلام BOOP وهي متوفرة بأحجام وعرض مختلفة. الاستعمال: تغليف الهدايا'),
(46, 43, 'en', 'stationary-tape-color-tape', 'Color Tape', 'Stationary Color tape is made with water based acrylic adhesive coated on BOOP films It available with different sizes and widths. Usage : gift wrapping , light packing , art craft , office application , paper mending and reinforcing documents .', 'Self Adhesive Tape | Stationary tape | Color Tape', 'Stationary Color tape is made with water based acrylic adhesive coated on BOOP films It available with different sizes and widths. Usage : gift wrapping'),
(47, 44, 'ar', 'السوليتب-المكتبى-ليزير-تيب', 'ليزير تيب', 'السوليتب المكتبى ليزير تيب مصنوع من مادة لاصقة أكريليك مائيّة مطلية بأفلام BOOP وهي متوفرة بأحجام وعرض مختلفة. الاستعمال: تغليف الهدايا ، التعبئة الخفيفة ، الأعمال الفنية ، التطبيقات المكتبية ، إصلاح الورق وتقوية المستندات.', 'الأشرطة ذاتية اللصق | السوليتب المكتبى | ليزير تيب', 'السوليتب المكتبى ليزير تيب مصنوع من مادة لاصقة أكريليك مائيّة مطلية بأفلام BOOP وهي متوفرة بأحجام وعرض مختلفة. الاستعمال: تغليف الهدايا'),
(48, 44, 'en', 'stationary-tape-laser-tape', 'Laser Tape', 'Stationary Laser tape is made with water based acrylic adhesive coated on BOOP films It available with different sizes and widths. Usage : gift wrapping , light packing , art craft , office application , paper mending and reinforcing documents .', 'Self Adhesive Tape | Stationary Tape | Laser Tape', 'Stationary Laser tape is made with water based acrylic adhesive coated on BOOP films It available with different sizes and widths. Usage : gift wrapping'),
(49, 45, 'ar', 'الاسترتش-الغذائى-هاى-ماكس', 'هاى ماكس', 'الاسترتش الغذائى هاى ماكس يستخدم في العديد من الاستخدامات فى تعبئة وتغليف الاطعامة وينشىء عازلا محكما يحافظ على نضارة ونكهة الاطعمة والمساعدة على التخلص من الروائح الكريهه فى الثلاجة \r\n\r\nمنتجنا الصديق للبيئة متعدد الاستخدامات وآمن ومناسب لجميع تغليف المواد الغذائية. من الممكن حتى في الثلاجة وفرن الميكروويف. يمكنه حماية الطعام الذي تريد حمايته بسرعة وتلبية متطلبات جميع احتياجات منزلك والمطبخ.', 'الاسترتش الغذائى هاى ماكس يستخدم لتعبئة وتغليف الاطعامة', 'هاى ماكس يستخدم في العديد من الاستخدامات فى تعبئة وتغليف الاطعامة وينشىء عازلا محكما يحافظ على نضارة ونكهة الاطعمة والمساعدة على التخلص من الروائح الكريهه'),
(50, 45, 'en', 'cling-warp-highmax-wrap', 'Highmax Wrap', 'Highmax Wrap is used in many actives for creates an airtight seal, locking in freshness and flavor while eliminating food odors in your refrigerator.\r\n\r\nOur environmentally friendly wrap are versatile and safe and suitable for all food packaging. It is feasible even in the refrigerator and microwave oven. It can quickly protect the food you want to protect and meet the requirements of all your home and kitchen needs.', 'Cling Warp Higmax Wrap used in many actives for creates an airtight', 'Highmax Wrap is used in many actives for creates an airtight seal, locking in freshness and flavor while eliminating food odors in your refrigerator'),
(51, 46, 'ar', 'الاسترتش-الغذائى-كومكس', 'كومكس', 'الاسترتش الغذائى كومكس يستخدم في العديد من الاستخدامات فى تعبئة وتغليف الاطعامة وينشىء عازلا محكما يحافظ على نضارة ونكهة الاطعمة والمساعدة على التخلص من الروائح الكريهه فى الثلاجة \r\n\r\nمنتجنا الصديق للبيئة متعدد الاستخدامات وآمن ومناسب لجميع تغليف المواد الغذائية. من الممكن حتى في الثلاجة وفرن الميكروويف. يمكنه حماية الطعام الذي تريد حمايته بسرعة وتلبية متطلبات جميع احتياجات منزلك والمطبخ.', 'الاسترتش الغذائى كومكس يستخدم لتعبئة وتغليف الاطعامة', 'كومكس يستخدم في العديد من الاستخدامات فى تعبئة وتغليف الاطعامة وينشىء عازلا محكما يحافظ على نضارة ونكهة الاطعمة والمساعدة على التخلص من الروائح الكريهه'),
(52, 46, 'en', 'cling-warp-komex', 'Komex', 'Komex Wrap is used in many actives for creates an airtight seal, locking in freshness and flavor while eliminating food odors in your refrigerator.\r\n\r\nOur environmentally friendly wrap are versatile and safe and suitable for all food packaging. It is feasible even in the refrigerator and microwave oven. It can quickly protect the food you want to protect and meet the requirements of all your home and kitchen needs.', 'Cling Warp Komex used in many actives for creates an airtight seal', 'Komex Wrap is used in many actives for creates an airtight seal, locking in freshness and flavor while eliminating food odors in your refrigerator'),
(53, 48, 'ar', 'الاسترتش-الغذائى-ستار-ماكسمم', 'ستار ماكسمم', 'ستار ماكسمم يستخدم في العديد من الاستخدامات فى تعبئة وتغليف الاطعامة وينشىء عازلا محكما يحافظ على نضارة ونكهة الاطعمة والمساعدة على التخلص من الروائح الكريهه فى الثلاجة \r\n\r\nمنتجنا الصديق للبيئة متعدد الاستخدامات وآمن ومناسب لجميع تغليف المواد الغذائية. من الممكن حتى في الثلاجة وفرن الميكروويف. يمكنه حماية الطعام الذي تريد حمايته بسرعة وتلبية متطلبات جميع احتياجات منزلك والمطبخ.', 'الاسترتش الغذائى | ستار ماكسمم يستخدم لتعبئة وتغليف الاطعامة', 'ستار ماكسمم يستخدم في العديد من الاستخدامات فى تعبئة وتغليف الاطعامة وينشىء عازلا محكما يحافظ على نضارة ونكهة الاطعمة والمساعدة على التخلص من الروائح الكريهه'),
(54, 48, 'en', 'cling-warp-star-maximum', 'Star Maximum', 'Star Maximum Wrap is used in many actives for creates an airtight seal, locking in freshness and flavor while eliminating food odors in your refrigerator.\r\n\r\nOur environmentally friendly wrap are versatile and safe and suitable for all food packaging. It is feasible even in the refrigerator and microwave oven. It can quickly protect the food you want to protect and meet the requirements of all your home and kitchen needs.', 'Cling Warp Star Maximum used in many actives for creates an airtight', 'Star Maximum Wrap is used in many actives for creates an airtight seal, locking in freshness and flavor while eliminating food odors in your refrigerator'),
(55, 49, 'ar', 'الاسترتش-الغذائى-هاى-ماكس-2', 'هاى ماكس', 'الاسترتش الغذائى هاى ماكس يستخدم في العديد من الاستخدامات فى تعبئة وتغليف الاطعامة وينشىء عازلا محكما يحافظ على نضارة ونكهة الاطعمة والمساعدة على التخلص من الروائح الكريهه فى الثلاجة \r\n\r\nمنتجنا الصديق للبيئة متعدد الاستخدامات وآمن ومناسب لجميع تغليف المواد الغذائية. من الممكن حتى في الثلاجة وفرن الميكروويف. يمكنه حماية الطعام الذي تريد حمايته بسرعة وتلبية متطلبات جميع احتياجات منزلك والمطبخ.', 'الاسترتش الغذائى | هاى ماكس يستخدم لتعبئة وتغليف الاطعامة', 'هاى ماكس يستخدم في العديد من الاستخدامات فى تعبئة وتغليف الاطعامة وينشىء عازلا محكما يحافظ على نضارة ونكهة الاطعمة والمساعدة على التخلص من الروائح الكريهه'),
(56, 49, 'en', 'cling-warp-highmax-wrap-2', 'Highmax Wrap', 'Highmax Wrap is used in many actives for creates an airtight seal, locking in freshness and flavor while eliminating food odors in your refrigerator.\r\n\r\nOur environmentally friendly wrap are versatile and safe and suitable for all food packaging. It is feasible even in the refrigerator and microwave oven. It can quickly protect the food you want to protect and meet the requirements of all your home and kitchen needs.', 'Cling Warp | Higmax Wrap used in many actives for creates an airtight', 'Highmax Wrap is used in many actives for creates an airtight seal, locking in freshness and flavor while eliminating food odors in your refrigerator'),
(57, 50, 'ar', 'مستر-فويل-للارجيلة', 'مستر فويل للارجيلة', 'رقائق الألومنيوم عالية الجودة للشيشة سيغطي معظم أوعية الشيشة الصغيرة والمتوسطة والكبيرة الحجم ، مما يمنحك تجربة استخدام لطيفة وممتعة. تعبئة مستقلة ، سهلة الحمل ، مناسبة للسفر ، الحفلات ، إلخ.', 'الومنيوم فويل للاستخدام الصناعى | مستر فويل للارجيلة', 'رقائق الألومنيوم عالية الجودة للشيشة سيغطي معظم أوعية الشيشة الصغيرة والمتوسطة والكبيرة الحجم ، مما يمنحك تجربة استخدام لطيفة وممتعة. تعبئة مستقلة'),
(58, 50, 'en', 'mr-foil-hookah-aluminum-foil', 'Mr Foil hookah aluminum foil', 'High quality hookah aluminum foil Role will cover most small and medium and large sized hookah bowls, giving you a nice and pleasant using experience. Independent packing, easy to carry, suitable for travel, party, etc.', 'Aluminium foil for Industry Use | Mr Foil hookah aluminum foil', 'High quality hookah aluminum foil Role will cover most small and medium and large sized hookah bowls, giving you a nice and pleasant using experience.'),
(59, 51, 'ar', 'غطاء-بوتاجز-مستر-فويل2', 'غطاء بوتاجز مستر فويل', 'غطاء بوتاجز مستر فويل عالي الجودة: مصنوعة من رقائق الألومنيوم عالية الجودة ، هذه العبوة من أغطية الموقد الفضية موصلة للحرارة بدرجة عالية ومتينة للغاية لتحقيق أقصى استخدام.\r\n\r\nتجنب متاعب تنظيف الحرق أو بقايا الطعام من سطح الفرن. لن تضطر أبدًا إلى القلق بشأن تنظيف الشعلات مرة أخرى!', 'الومنيوم فويل للاستخدام الصناعى | غطاء بوتاجز مستر فويل', 'غطاء بوتاجز مستر فويل عالي الجودة: مصنوعة من رقائق الألومنيوم عالية الجودة ، هذه العبوة من أغطية الموقد الفضية موصلة للحرارة بدرجة عالية ومتينة للغاية لتحقيق'),
(60, 51, 'en', 'mr-foil-oven-2', 'Mr Foil Oven', 'Disposable Burner Covers For Gas Stoves Superior Quality Aluminum Foil: Made of high quality aluminum foil, this pack of silver burner covers are highly heat conducive and extra durable for maximum usage. \r\n\r\nAvoid the hassle of scrubbing out burn or food residue from your oven surface. you’ll never have to stress about cleaning your burners again!', 'Aluminium foil for Industry Use | Mr Foil Oven', 'Disposable Burner Covers For Gas Stoves Superior Quality Aluminum Foil: Made of high quality aluminum foil, this pack of silver burner covers are highly heat'),
(61, 52, 'ar', 'غطاء-بوتاجز-مستر-فويل', 'غطاء بوتاجز مستر فويل', 'غطاء بوتاجز مستر فويل عالي الجودة: مصنوعة من رقائق الألومنيوم عالية الجودة ، هذه العبوة من أغطية الموقد الفضية موصلة للحرارة بدرجة عالية ومتينة للغاية لتحقيق أقصى استخدام.\r\n\r\nتجنب متاعب تنظيف الحرق أو بقايا الطعام من سطح الفرن. لن تضطر أبدًا إلى القلق بشأن تنظيف الشعلات مرة أخرى!', 'الومنيوم فويل للاستخدام الصناعى | غطاء بوتاجز مستر فويل', 'غطاء بوتاجز مستر فويل عالي الجودة: مصنوعة من رقائق الألومنيوم عالية الجودة ، هذه العبوة من أغطية الموقد الفضية موصلة للحرارة بدرجة عالية ومتينة للغاية لتحقيق'),
(62, 52, 'en', 'mr-foil-oven', 'Mr Foil Oven', 'Disposable Burner Covers For Gas Stoves Superior Quality Aluminum Foil: Made of high quality aluminum foil, this pack of silver burner covers are highly heat conducive and extra durable for maximum usage. \r\n\r\nAvoid the hassle of scrubbing out burn or food residue from your oven surface. you’ll never have to stress about cleaning your burners again!', 'Aluminium foil for Industry Use | Mr Foil Oven', 'Disposable Burner Covers For Gas Stoves Superior Quality Aluminum Foil: Made of high quality aluminum foil, this pack of silver burner covers are highly heat'),
(63, 53, 'ar', 'الومنيوم-فويل-كينك', 'الومنيوم فويل كينك', 'العلامة التجارية رقم 1 لرقائق الألمنيوم المصنوعة في مصر ، الومنيوم فويل كينك بالقوة والجودة الموثوق بها التي يمكنك الاعتماد عليها لطهي وجبات لذيذة مع سهولة التنظيف\r\nسميكة جدًا للطبخ في الفرن أو على الشواية أو على النار ؛ يسمح للطهي لفترة أطول من أجل شواء اللحوم بشكل أفضل.يساعدك صندوق الورق المقوى المزود بقاطع معدني على تمزيق ورق القصدير بشكل أكثر كفاءة وراحة.', 'الومنيوم فويل استخدام منزلى | الومنيوم فويل كينك', 'العلامة التجارية رقم 1 لرقائق الألمنيوم المصنوعة في مصر ، الومنيوم فويل كينك بالقوة والجودة الموثوق بها التي يمكنك الاعتماد عليها لطهي وجبات لذيذة مع سهولة'),
(64, 53, 'en', 'aluminium-foil-king', 'Aluminium foil King', 'The number 1 brand of aluminum foil made in the Egypt, MR. FOIL has the trusted strength and quality you can count on for cooking delicious meals with easy cleanup \r\nExtra thickened for cooking in the oven, on the grill or over a fire; allows for longer cooking limiting to better broil the meats.\r\nPaper board box with metal cutter help you to tear off the foil paper more efficiently and conveniently.', 'Aluminium foil for House Hold | Aluminium foil King', 'The number 1 brand of aluminum foil made in the Egypt, King has the trusted strength and quality you can count on for cooking delicious meals'),
(65, 55, 'ar', 'جامبو-رول', 'جامبو رول', 'جامبو رول', 'جامبو رول', 'جامبو رول'),
(66, 55, 'en', 'jumbo-roll', 'Jumbo Roll', 'جامبو رول', 'Jumbo Roll', 'جامبو رول'),
(67, 56, 'ar', 'مسدس-شمع-بسلك-كهرباء-من-يوني-تي-موديل-eh430', 'مسدس شمع بسلك كهرباء من يوني-تي موديل EH430', 'العلامة التجارية: يوني-تي\r\nمصدر الطاقة: سلك كهربائي\r\nنوع المنتج: مسدس شمع\r\nرقم الموديل: EH430\r\nهل يعمل المنتج بالبطارية أم المنتج بطارية: لا\r\nهل يعتبر هذا المنتج خطر أو مصنوع من خامة أو مادة خطيرة ولكن يصلح للنقل أو التخزين و/أو التخلص منه؟: لا', 'مسدس شمع بسلك كهرباء من يوني-تي موديل EH430', 'مسدس شمع بسلك كهرباء من يوني-تي موديل EH430'),
(68, 56, 'en', 'مسدس-شمع-بسلك-كهرباء-من-يوني-تي-موديل-eh430', 'مسدس شمع بسلك كهرباء من يوني-تي موديل EH430', 'العلامة التجارية: يوني-تي\r\nمصدر الطاقة: سلك كهربائي\r\nنوع المنتج: مسدس شمع\r\nرقم الموديل: EH430\r\nهل يعمل المنتج بالبطارية أم المنتج بطارية: لا\r\nهل يعتبر هذا المنتج خطر أو مصنوع من خامة أو مادة خطيرة ولكن يصلح للنقل أو التخزين و/أو التخلص منه؟: لا', 'مسدس شمع بسلك كهرباء من يوني-تي موديل EH430', 'مسدس شمع بسلك كهرباء من يوني-تي موديل EH430'),
(69, 57, 'ar', 'مسدس-شمع-st-03-20w-حجم-صغير-ازرق', 'مسدس شمع ST-03 20W، حجم صغير - ازرق', NULL, '221', NULL),
(70, 57, 'en', 'مسدس-شمع-st-03-20w-حجم-صغير-ازرق', 'مسدس شمع ST-03 20W، حجم صغير - ازرق', NULL, NULL, NULL),
(71, 58, 'ar', 'مسدس-شمع-برو-جلو-من-ستانلي-gr100', 'مسدس شمع برو جلو من ستانلي GR100', NULL, '475', NULL),
(72, 58, 'en', 'مسدس-شمع-برو-جلو-من-ستانلي-gr100', 'مسدس شمع برو جلو من ستانلي GR100', NULL, NULL, NULL),
(73, 59, 'ar', 'مسدس-شمع-من-عتمان-جروب-متعدد-الألوان', 'مسدس شمع من عتمان جروب، متعدد الألوان', NULL, '138', NULL),
(74, 59, 'en', 'مسدس-شمع-من-عتمان-جروب-متعدد-الألوان', 'مسدس شمع من عتمان جروب، متعدد الألوان', NULL, NULL, NULL),
(75, 60, 'ar', 'مسدس-غراء-احترافي-220-وات-من-توتال-tt301116', 'مسدس غراء احترافي 220 وات من توتال TT301116', 'اللون 	أزرق/أحمر/أبيض\r\nاسم العلامة التجارية 	توتال تولز\r\nالنمط 	زناد\r\nأبعاد السلعة 	34,5 x 24 x 6 سم\r\nمصدر الطاقة 	سلك كهربائي\r\nالقوة الكهربائية 	220 واط\r\nأبعاد المنتج الطول × العرض × الارتفاع 	35,4L x 6W x 24H سم', '334', NULL),
(76, 60, 'en', 'مسدس-غراء-احترافي-220-وات-من-توتال-tt301116', 'مسدس غراء احترافي 220 وات من توتال TT301116', NULL, NULL, NULL);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
